import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";
import { loadBundle } from "./support/load-bundle.mjs";
const { exports: { OwnedDirectories, StateStore, LocalRequests, fullDigest } } = await loadBundle("tests/support/headless-entry.ts");
const root = fs.mkdtempSync(path.join(tmpdir(), "fns-local-"));
const vault = path.join(root, "vault"), state = path.join(root, "state");
fs.mkdirSync(vault); fs.mkdirSync(state);
const owner = OwnedDirectories.acquire(vault, state);
let store = new StateStore(path.join(state, "state.db"), { create: true });
let requests = new LocalRequests(owner, store, "controlled");
const content = text => Buffer.from(text);
const version = text => ({ sha256: fullDigest(content(text)), size: content(text).length });
const write = (id, operation, text, expected, file = "note.md") => ({ requestId: id, operation, path: file, contentKind: "note", content: content(text), expected });
const rename = (id, source, target, expected) => ({ requestId: id, operation: "rename", path: source, targetPath: target, targetExpected: null, contentKind: "note", expected });
try {
  assert.throws(() => new LocalRequests(owner, store), error => error.code === "local-writer-contract-required");
  const created = await requests.submit(write("create-1", "create", "first", null));
  assert.equal(created.status, "applied"); assert.equal(created.synchronization, "not-confirmed");
  assert.deepEqual(await requests.submit(write("create-1", "create", "first", null)), created);
  await assert.rejects(requests.submit(write("create-1", "create", "changed-payload", null)), error => error.code === "request-id-reused");
  const stale = await requests.submit(write("stale-1", "modify", "must-not-win", version("older")));
  assert.equal(stale.status, "stale"); assert.equal(owner.vault.read("note.md").toString(), "first");
  assert.deepEqual(await requests.submit(write("stale-1", "modify", "must-not-win", version("older"))), stale);
  assert.equal((await requests.submit(write("modify-1", "modify", "second", version("first")))).status, "applied");
  const reordered = write("modify-1", "modify", "second", { size: 5, sha256: version("first").sha256 });
  assert.equal((await requests.submit(reordered)).status, "applied", "Property order must not change the request fingerprint");
  await requests.submit(write("target-1", "create", "occupied", null, "other.md"));
  assert.equal((await requests.submit(rename("rename-blocked", "note.md", "other.md", version("second")))).reason, "target-exists");
  assert.equal(owner.vault.read("other.md").toString(), "occupied");
  assert.equal((await requests.submit(rename("rename-case", "note.md", "Note.md", version("second")))).status, "applied");
  assert.equal(owner.vault.read("Note.md").toString(), "second");
  owner.vault.createDirectory("nested");
  assert.equal((await requests.submit(rename("rename-cross", "Note.md", "nested/note.md", version("second")))).status, "applied");
  assert.equal(owner.vault.readOptional("Note.md"), null);
  const deletion = { requestId: "delete-1", operation: "delete", path: "nested/note.md", expected: version("second"), contentKind: "note" };
  const deleted = await requests.submit(deletion);
  assert.equal(deleted.status, "applied"); assert.equal(owner.vault.readOptional("nested/note.md"), null);
  await requests.submit(write("create-after-delete", "create", "third", null, "nested/note.md"));
  assert.deepEqual(await requests.submit(deletion), deleted);
  assert.equal(owner.vault.read("nested/note.md").toString(), "third", "Idempotent delete must not remove a subsequently created file");
  store.close(); store = new StateStore(path.join(state, "state.db")); requests = new LocalRequests(owner, store, "controlled");
  assert.deepEqual(await requests.submit(deletion), deleted);
  assert.equal(owner.vault.read("nested/note.md").toString(), "third");
  const competing = await Promise.all([requests.submit(write("compete-a", "modify", "A", version("third"), "nested/note.md")), requests.submit(write("compete-b", "modify", "B", version("third"), "nested/note.md"))]);
  assert.deepEqual(competing.map(value => value.status), ["applied", "stale"]);
  assert.equal(owner.vault.read("nested/note.md").toString(), "A");
  assert.equal(store.list("baseline").length, 0);
  const same = version("A");
  await requests.submit({ requestId: "delete-case", operation: "delete", path: "nested/note.md", expected: same, contentKind: "note" });
  await requests.submit(write("recreate-case", "create", "A", null, "nested/Note.md"));
  assert.equal((await requests.submit(write("modify-case", "modify", "B", same, "nested/Note.md"))).status, "applied", "Old delete cleanup must not inspect a successor's differently cased name");
  console.log("local-requests.test.mjs: four operations, preconditions, idempotency, case rename and restart passed");
} finally { store.close(); owner.close(); fs.rmSync(root, { recursive: true, force: true }); }
